name: Build Static Site

on:
  push:
    paths:
      - 'product_names.csv'
      - 'prices.json'
      - 'index-template.html'
      - 'build.js'
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
      
    - name: Build static site
      run: node build.js
      
    - name: Commit and push generated HTML
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add index.html
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Auto-update static site: $(date)"
          git push
        fi
