name: Update Product Prices and Generate Static Site

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
  push:
    paths:
      - 'product_asin.csv'
      - 'index-template.html'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pages: write
      id-token: write
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install Python dependencies
      run: |
        pip install pandas requests
        
    - name: Verify required files
      run: |
        echo "Checking for required files..."
        ls -la
        if [ ! -f "product_asin.csv" ]; then
          echo "Warning: product_asin.csv file not found"
        else
          echo "Found product_asin.csv"
          head -5 product_asin.csv
        fi
        if [ ! -f "generate-static-site.js" ]; then
          echo "Error: generate-static-site.js not found"
          exit 1
        fi
        if [ ! -f "scraper.py" ]; then
          echo "Error: scraper.py not found"
          exit 1
        fi
        
    - name: Run EcommerceAPI price fetcher
      env:
        ECOMMERCE_API_KEY: ${{ secrets.ECOMMERCE_API_KEY }}
      run: |
        echo "Starting price fetch with EcommerceAPI..."
        python scraper.py || {
          echo "Scraper failed, checking for existing data..."
          if [ ! -f "products.json" ]; then
            echo "No existing data found, creating empty structure"
            echo '[]' > products.json
          else
            echo "Using existing products.json data"
          fi
        }
        
    - name: Verify products data
      run: |
        if [ -f "products.json" ]; then
          echo "Products data exists"
          echo "File size: $(wc -c < products.json) bytes"
          echo "Products structure preview:"
          head -10 products.json
        else
          echo "No products.json found after scraping"
        fi
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Create fallback data if needed
      run: |
        if [ ! -f "products.json" ]; then
          echo "Creating fallback products.json with empty array structure"
          echo '[]' > products.json
        fi
        
    - name: Generate static HTML
      run: |
        echo "Generating static HTML site..."
        node generate-static-site.js
        
    - name: Verify generated files
      run: |
        if [ ! -f "index.html" ]; then
          echo "Error: index.html was not generated"
          exit 1
        fi
        echo "Generated files successfully:"
        ls -la *.html *.json
        echo "index.html size: $(wc -c < index.html) bytes"
        
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload to GitHub Pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: '.'
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
        
    - name: Commit updated files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        if [ -f "products.json" ]; then
          git add products.json
        fi
        if [ -f "index.html" ]; then
          git add index.html
        fi
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Auto-update prices and site: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
          git push
        fi
        
    - name: Summary
      run: |
        echo "Deployment completed successfully"
        echo "Site URL: ${{ steps.deployment.outputs.page_url }}"
